version: '3.8'

services:
  mysqldb:
    image: mysql/mysql-server
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=manufacturers
    volumes:
      - mysql:/var/lib/mysql
  web:
    build:
      context: ./web_service
    depends_on:
      - mysqldb
    ports:
      - 8000:5000
    volumes:
      - ./web_service:/DNL/web_service

volumes:
  mysql:
